### ISSUE TITLE
Error relocating mini_racer_extension.so: backtrace_symbols: symbol not found on 2.5-alpine and 2.6-alpine

### ISSUE THREAD

**Issue by lloeki** [sqreen/ruby-libv8-node#25]
see e.g [here](https://github.com/sqreen/ruby-libv8-node/runs/3920342792?check_suite_focus=true)

```
/home/runner/work/ruby-libv8-node/ruby-libv8-node/test/mini_racer/lib/mini_racer.rb:11:in `load': Error relocating /home/runner/work/ruby-libv8-node/ruby-libv8-node/test/mini_racer/lib/mini_racer_extension.so: backtrace_symbols: symbol not found (LoadError)
152
	from /home/runner/work/ruby-libv8-node/ruby-libv8-node/test/mini_racer/lib/mini_racer.rb:11:in `<top (required)>'
```

**Comment by lloeki** [comment]
Turns out the musl build is OK, it's just old Rubygems having `nil` as a version instead of `musl`, therefore it fetches the incorrect one.

**Comment by seanmakesgames** [comment]
we aren't supporting 2.5 and 2.6 anymore. Is this issue still valid?
