### ISSUE TITLE
Add Linux ARM targets

### ISSUE THREAD

**Issue by lloeki** [sqreen/ruby-libv8-node#8]
Possible on CI via qemu and/or xbuild

Considered targets:

- aarch64
- armv7
- armv8

**Comment by lloeki** [comment]
Currently built manually inside an aarch64 Linux VM on a M1 Mac Mini. Appears to run fine on Linux on ARM hardware (Graviton) but [has trouble at runtime on emulated machines](https://github.com/rubyjs/mini_racer/issues/190) (via qemu on x86 and/or docker's hyperkit on M1)

**Comment by lloeki** [comment]
Cross-compiling builds correctly, but I hit a missing symbol error.

```
root@5e26cbbca17e:/mini_racer# bundle exec rake test
/usr/local/bin/ruby: symbol lookup error: /mini_racer/lib/mini_racer_extension.so: undefined symbol: _ZN2v82V818SetFlagsFromStringEPKcm
rake aborted!
root@5e26cbbca17e:/mini_racer# echo _ZN2v82V818SetFlagsFromStringEPKcm | c++filt 
v8::V8::SetFlagsFromString(char const*, unsigned long)
```

**Comment by lloeki** [comment]
It seems compilation was partial, the intermediate `libv8_monolith.a` target might have been insufficient for cross-compilation to fully proceed (e.g `api.o` from `v8_base_without_compiler` was only present in `obj.host` and absent from `obj.target`), but running a full `make` produced all the required `.o` in `obj.target`.

**Comment by tisba** [comment]
> Currently built manually inside an aarch64 Linux VM on a M1 Mac Mini. Appears to run fine on Linux on ARM hardware (Graviton) but [has trouble at runtime on emulated machines](https://github.com/rubyjs/mini_racer/issues/190) (via qemu on x86 and/or docker's hyperkit on M1)

Just a tiny remark: Docker for Desktop does also have experimental support for Big Sur/MacOS virtualization.framework. The same problem exists there though. Docker's hyperkit VM was/is based on hypervisor.framework.

**Comment by lloeki** [comment]
Got a build and a gem working! Not publishing yet because things are not ready automation-side but testers are welcome to make themselves known.

**Comment by lloeki** [comment]
@tisba I have Linux cross compilation to ARM on x64 CI working, [see this run](https://github.com/sqreen/ruby-libv8-node/actions/runs/1016185701) (there are some failures but they're on Darwin and Alpine, gnu/ARM passes!)

Before I pull the trigger and publish these, can you download the `gem-16.3.0.0-aarch64-linux` down the summary page and try it out [as you did over there](https://github.com/rubyjs/mini_racer/issues/190#issuecomment-865910526)?

**Comment by tisba** [comment]
For some reason I'm getting an error when I try to `gem unpack` the gem. I'll take a closer look later.

```
$ gem unpack gems/libv8-node-16.3.0.0-aarch64-linux.gem --target gems/libv8-node-16.3.0.0-aarch64-linux/
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `ArgumentError' at /Users/basti/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/package/tar_header.rb:129 - "\xF7\xA0\aw\xB7\x83\xBBs" is not an octal string
ERROR:  While executing gem ... (ArgumentError)
    "\xF7\xA0\aw\xB7\x83\xBBs" is not an octal string
        /Users/basti/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/package/tar_header.rb:129:in `strict_oct'
        /Users/basti/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/package/tar_header.rb:107:in `from'
        /Users/basti/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:59:in `each'
        /Users/basti/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:112:in `find'
        /Users/basti/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:112:in `seek'
[SNIP]
```

**Comment by lloeki** [comment]
There's another build based on 16.4.2 over there: https://github.com/sqreen/ruby-libv8-node/actions/runs/1023202498

**Comment by tisba** [comment]
I'm not sure what I'm doing "wrong" 😞 

I downloaded https://github.com/sqreen/ruby-libv8-node/suites/3216862858/artifacts/74504625 as `gems/gem-16.4.2.0-aarch64-linux.gem` and run `gem generate_index` (both natively on M1 and x86 Ruby 3.0.2 or via `docker run -it --rm -v "$(pwd)":/app -w /app ruby:3.0.2`) and still getting the same error...

```
ERROR:  Unable to process /app/gems/gem-16.4.2.0-aarch64-linux.gem
"f:bff<\xA2#" is not an octal string (ArgumentError)
        /usr/local/lib/ruby/3.0.0/rubygems/package/tar_header.rb:129:in `strict_oct'
        /usr/local/lib/ruby/3.0.0/rubygems/package/tar_header.rb:107:in `from'
        /usr/local/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:59:in `each'
        /usr/local/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:112:in `find'
        /usr/local/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:112:in `seek'
        /usr/local/lib/ruby/3.0.0/rubygems/package.rb:544:in `read_checksums'
```

To sanity check, I downloaded https://rubygems.org/downloads/rails-6.1.4.gem and `gem generate_index` (and `gem unpack`) works. Does this work for you, @lloeki? What am I missing?

* `ruby --version` 3.0.2p107
* `gem --version` 3.2.23

**Comment by tisba** [comment]
Any ideas, @lloeki?

**Comment by lloeki** [comment]
Sorry for the delay @tisba, I did not have a moment to look at this but I'm not forgetting about it!

**Comment by tisba** [comment]
For reference: mini_racer 0.6.2 with `MiniRacer::Platform.set_flags!(:single_threaded)` works now even with forking and on `aarch64-linux`, `x86_64-linux`, `arm64-darwin21` and `x86_64-darwin21`.

I think what is "missing" for Linux ARM targets is mostly musl libc builds.
